displayName=Who Can Craft
author=sleepmusic
description=Find who in your GIM can craft an item or who is closest. 
tags=craft, progression, GIM, group ironman, GIM craft
version=
plugins=com.WhoCanCraft.WhoCanCraftPlugin
build=standard